version: '3.4'

services:
  teamfiercebackendpython:
    image: teamfiercebackendpython
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5412:8000
    depends_on: 
      - worker
      - broker
  
  broker:
    image: rabbitmq:latest
    hostname: broker
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
    
  worker:
    image: teamfiercebackendpython
    restart: "no"
    command: celery -A send_email_microservice worker -l info
    volumes:
      - .:/code
    depends_on:
      - broker
